/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'fractal-resonance-cognition', // The "Bridge" page is the root
    },
    {
      type: 'category',
      label: 'The 16D Protocol (v2)',
      items: [
        {
          type: 'autogenerated',
          dirName: '16d-protocol', // Auto-generates from the folder
        },
      ],
    },
    {
      type: 'category',
      label: 'The 821 Physics Series',
      items: [
        {
          type: 'autogenerated',
          dirName: '821-physics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Foundations (Prime 1)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'foundations',
        },
      ],
    },
  ],
};

export default sidebars;
